---
- name: open-ports
  src: git@github.com:status-im/infra-role-open-ports.git
  version: 24dc30dbdf85e6758cb6924074b2f7a0f4541524
  scm: git

- name: swap-file
  src: git@github.com:status-im/infra-role-swap-file.git
  version: 3fb0fb8d313ab388df1b38d516e2ff88b72a2cf7
  scm: git

- name: infra-role-bootstrap-linux
  src: git@github.com:status-im/infra-role-bootstrap-linux.git
  version: c9ba56896f75e4669d2f949d04726bc8fe82a534
  scm: git

- name: infra-role-wireguard
  src: git@github.com:status-im/infra-role-wireguard.git
  version: 6c83e0bdcecba772e5c652c89e1995865d14c662
  scm: git

- name: consul-service
  src: git@github.com:status-im/infra-role-consul-service.git
  version: 4849a3c9d7f2045669880e4e17eeb71980b2e4d0
  scm: git

- name: infra-role-geth
  src: git@github.com:status-im/infra-role-geth.git
  version: c2f7fac2a0c2a36bfbf4aa0c0c46dfea2f875b6c
  scm: git

- name: infra-role-nim-codex
  src: git@github.com:status-im/infra-role-nim-codex.git
  version: 246eed3ff3209bcb31b48cbf4a6d56f525993a48
  scm: git

- name: systemd-timer
  src: git@github.com:status-im/infra-role-systemd-timer.git
  version: 0cc94695f3dada39213a87fbe923cd90e2a7d2c2
  scm: git
